general {
    hide_cursor = true
}
background {
    monitor =
    color = rgb(222222)
}
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    inner_color = rgb(222222)
    outer_color = rgb(c9a554)
    font_color = rgb(d7c483)
    font_family = Iosevka Nerd Font
    placeholder_text = Password
    fade_on_empty = false
    rounding = 4
    position = 0, -20
    halign = center
    valign = center
}
